### ISSUE TITLE
Only Last Event Displayed When Multiple Events Have Same Name

### ISSUE THREAD

**Issue by chinzhening** [baptiste/yaml-dadaism#1]
## Description
When I create two or more events with the same title but different dates, only the last event is displayed in the calendar. The previous events with the same name are overwritten or not rendered.

## Steps to Reproduce:
1. Write this in the yaml file:
```yml
"Conference":
  Type: event
  Start: 2025-05-23
  End: 2025-05-23
"Conference":
  Type: event
  Start: 2025-05-25
  End: 2025-05-25
"Conference":
  Type: event
  Start: 2025-05-30
  End: 2025-05-30
```
2. Observe that only the conference event on 2025-05-30 appears in the calendar. [main.pdf](https://github.com/user-attachments/files/20411197/main.pdf)

All events should be displayed, even if they share the same title.
